services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tycoon-web
    ports:
      - "8000:8000"

    env_file: .env
    depends_on:
      - db

  db:
    image: postgres
    container_name: tycoon-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: testpw
      POSTGRES_DB: tycoon
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
